namespace SparkDevNetwork.Rock.CodeGenerator
{
    /// <summary>
    /// Provides any strings required by the generator to produce output.
    /// </summary>
    public interface IGeneratorStringsProvider
    {
        /// <summary>
        /// The comment to put at the top of the file to designate that this
        /// is an auto-generated file that will be overwritten.
        /// </summary>
        string AutoGeneratedComment { get; }

        /// <summary>
        /// The comment that contains any copyright information to include in
        /// the generated file.
        /// </summary>
        string CopyrightComment { get; }
    }
}
