using SparkDevNetwork.Rock.CodeGenerator;

namespace SparkDevNetwork.Rock.DevTool.Generators;

/// <summary>
/// The strings that will be used by code generators for comments and such.
/// </summary>
class GeneratorStrings : IGeneratorStringsProvider
{
    /// <inheritdoc/>
    public string AutoGeneratedComment => "// This code was auto-generated, any manual changes made will be lost.\n\n";

    /// <inheritdoc/>
    public string CopyrightComment => string.Empty;
}

