name: Publish

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v[1-9].*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --output .
    - name: List
      run: ls -l *.nupkg
    # - name: Publish
    #   run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
