name: Publish

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v[1-9].*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Restore C# dependencies
      run: dotnet restore
    - name: Restore eslint-config-rock-recommended dependencies
      run: npm ci
      working-directory: ./src/eslint-config-rock-recommended
    - name: Restore obsidian-build-tools dependencies
      run: npm ci
      working-directory: ./src/obsidian-build-tools
    - name: Build C#
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack C#
      run: dotnet pack --output .
    - name: Build obsidian-build-tools
      run: npm run build
      working-directory: ./src/obsidian-build-tools
    - name: Pack obsidian-build-tools
      run: npm pack --pack-destination ../..
      working-directory: ./src/obsidian-build-tools
    - name: Archive NuGet packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: "*.nupkg"
        if-no-files-found: error
        retention-days: 30
    - name: Archive npm packages
      uses: actions/upload-artifact@v4
      with:
        name: npm-packages
        path: "*.tgz"
        if-no-files-found: error
        retention-days: 30
    # - name: Publish
    #   run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
